print_int (int_of_float (3.5 +. 2.5));
print_int (int_of_float (3.5 -. 2.5));
print_int (int_of_float (2.5 *. 0.4));
print_int (int_of_float (1.0 /. 0.2));
print_int (int_of_float (sqrt 4.0));
print_int (int_of_float (sin 0.0));
print_int (int_of_float (cos 0.0));
print_int (int_of_float (atan 0.0));
print_int (int_of_float (fhalf 4.0));
print_int (int_of_float (fsqr 2.0));
print_int (int_of_float (fabs (-2.0)));
print_int (int_of_float (float_of_int 5));